default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: meal-ordering_development

test:
  <<: *default
  database: meal-ordering_test

production:
  <<: *default
  database: meal-ordering_production
  username: meal-ordering
  password: <%= ENV['MEAL-ORDERING_DATABASE_PASSWORD'] %>
